ml_core:
  model_type: "transformer"
  batch_size: 32
  learning_rate: 0.001
  model_path: "models/"
  
energy_optimizer:
  monitoring_interval: 60
  power_modes:
    - balanced
    - performance
    - power_saver
  log_file: "logs/energy.log"

api:
  host: "0.0.0.0"
  port: 8000
  rate_limit: 100
  api_key: "${API_KEY}"
  cors_origins:
    - "http://localhost:3000"
    - "https://your-frontend-domain.com"
  log_file: "logs/api.log"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"